#include "encstrset.h"

#ifdef NDEBUG
	#undef NDEBUG
#endif

#include <cassert>

int main() {
assert(::jnp1::encstrset_test(21372137, "", "X") == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_remove(21372137, "FL", "FL") == false);
::jnp1::encstrset_copy(21372137, 21372137);
assert(::jnp1::encstrset_insert(21372137, nullptr, "FL") == false);
assert(::jnp1::encstrset_insert(21372137, nullptr, NULL) == false);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_insert(21372137, "FL", "CS") == false);
assert(::jnp1::encstrset_remove(21372137, "X", NULL) == false);
int s0 = ::jnp1::encstrset_new();
assert(::jnp1::encstrset_remove(21372137, NULL, "EE") == false);
assert(::jnp1::encstrset_remove(21372137, "EE", nullptr) == false);
int s1 = ::jnp1::encstrset_new();
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_insert(s0, "BG", "X") == true);
assert(::jnp1::encstrset_insert(s1, "X", "FL") == true);
assert(::jnp1::encstrset_insert(21372137, "BG", "BUBT") == false);
int s2 = ::jnp1::encstrset_new();
assert(::jnp1::encstrset_size(s2) == 0);
assert(::jnp1::encstrset_insert(s2, nullptr, "CS") == false);
int s3 = ::jnp1::encstrset_new();
assert(::jnp1::encstrset_insert(s1, "BUBT", nullptr) == true);
::jnp1::encstrset_copy(s0, s1);
assert(::jnp1::encstrset_insert(21372137, "X", "CS") == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_size(s3) == 0);
::jnp1::encstrset_clear(21372137);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_size(s0) == 1);
assert(::jnp1::encstrset_insert(s0, "BUBT", "CS") == true);
assert(::jnp1::encstrset_insert(s1, "CS", "BG") == true);
assert(::jnp1::encstrset_size(s1) == 1);
assert(::jnp1::encstrset_insert(s1, "BSTB", "CS") == true);
::jnp1::encstrset_copy(s0, s2);
assert(::jnp1::encstrset_insert(21372137, NULL, "CS") == false);
::jnp1::encstrset_copy(s2, s3);
assert(::jnp1::encstrset_size(s2) == 2);
assert(::jnp1::encstrset_test(21372137, "BUBT", "") == false);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_remove(s2, "CS", "PSL") == false);
::jnp1::encstrset_copy(s3, s1);
::jnp1::encstrset_copy(s3, s2);
assert(::jnp1::encstrset_insert(s3, "FL", "X") == true);
assert(::jnp1::encstrset_size(s1) == 4);
assert(::jnp1::encstrset_test(s1, "X", "X") == false);
assert(::jnp1::encstrset_insert(21372137, "BUBT", "X") == false);
::jnp1::encstrset_copy(s2, s0);
assert(::jnp1::encstrset_insert(s0, "FL", "") == true);
int s4 = ::jnp1::encstrset_new();
assert(::jnp1::encstrset_insert(s4, "BG", "BG") == true);
::jnp1::encstrset_copy(s0, 21372137);
::jnp1::encstrset_copy(s0, s1);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_insert(s2, "X", "BSTB") == true);
assert(::jnp1::encstrset_remove(s2, "EE", "EE") == false);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_insert(21372137, "BSTB", NULL) == false);
::jnp1::encstrset_copy(21372137, s2);
assert(::jnp1::encstrset_remove(s3, NULL, "") == false);
assert(::jnp1::encstrset_size(s1) == 0);
assert(::jnp1::encstrset_insert(s4, "X", "EE") == true);
assert(::jnp1::encstrset_insert(s4, "FL", "BUBT") == true);
assert(::jnp1::encstrset_insert(21372137, "BUBT", "") == false);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_remove(s3, "CS", "BSTB") == false);
::jnp1::encstrset_copy(s0, s4);
assert(::jnp1::encstrset_test(21372137, nullptr, "EE") == false);
::jnp1::encstrset_copy(21372137, s1);
::jnp1::encstrset_copy(s1, s0);
assert(::jnp1::encstrset_insert(s2, "BUBT", nullptr) == true);
assert(::jnp1::encstrset_test(21372137, nullptr, "") == false);
assert(::jnp1::encstrset_test(s3, "X", "BUBT") == false);
assert(::jnp1::encstrset_insert(21372137, "BUBT", "BUBT") == false);
assert(::jnp1::encstrset_remove(s2, "FL", "") == false);
assert(::jnp1::encstrset_size(s0) == 3);
assert(::jnp1::encstrset_insert(s4, "PSL", "") == true);
assert(::jnp1::encstrset_size(s0) == 3);
::jnp1::encstrset_copy(21372137, 21372137);
::jnp1::encstrset_copy(s1, s2);
assert(::jnp1::encstrset_size(s4) == 7);
::jnp1::encstrset_copy(s1, 21372137);
assert(::jnp1::encstrset_insert(s4, "BSTB", nullptr) == true);
assert(::jnp1::encstrset_insert(s1, "X", "FL") == true);
assert(::jnp1::encstrset_insert(s4, "CS", "EE") == true);
::jnp1::encstrset_copy(s0, s1);
assert(::jnp1::encstrset_insert(s0, "", "CS") == true);
assert(::jnp1::encstrset_insert(21372137, "CS", "CS") == false);
::jnp1::encstrset_copy(s3, 21372137);
::jnp1::encstrset_copy(s3, s1);
assert(::jnp1::encstrset_remove(s1, NULL, "FL") == false);
::jnp1::encstrset_copy(s1, s4);
::jnp1::encstrset_copy(s3, s3);
::jnp1::encstrset_copy(s2, s4);
::jnp1::encstrset_copy(s2, s3);
::jnp1::encstrset_copy(s0, s0);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_size(s1) == 4);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_insert(s0, "", "BUBT") == false);
assert(::jnp1::encstrset_test(s0, "X", "FL") == false);
assert(::jnp1::encstrset_test(s4, "", "CS") == false);
::jnp1::encstrset_copy(s3, 21372137);
assert(::jnp1::encstrset_test(s0, "BUBT", NULL) == false);
assert(::jnp1::encstrset_insert(21372137, "FL", "") == false);
::jnp1::encstrset_copy(s3, 21372137);
::jnp1::encstrset_copy(s2, 21372137);
assert(::jnp1::encstrset_insert(s4, "PSL", "BG") == true);
assert(::jnp1::encstrset_insert(s0, "FL", "") == false);
assert(::jnp1::encstrset_insert(s0, "X", "BSTB") == true);
::jnp1::encstrset_copy(s2, s3);
assert(::jnp1::encstrset_test(s0, "", "") == true);
assert(::jnp1::encstrset_size(s0) == 5);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_copy(s1, s4);
assert(::jnp1::encstrset_test(s4, "FL", "FL") == true);
assert(::jnp1::encstrset_remove(s4, "", "CS") == false);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_insert(s4, nullptr, nullptr) == false);
assert(::jnp1::encstrset_remove(s2, "", "") == false);
::jnp1::encstrset_copy(s1, s2);
assert(::jnp1::encstrset_size(s1) == 4);
assert(::jnp1::encstrset_test(s4, "BG", "EE") == false);
assert(::jnp1::encstrset_insert(s1, nullptr, "BUBT") == false);
assert(::jnp1::encstrset_insert(21372137, "CS", "CS") == false);
assert(::jnp1::encstrset_test(s1, nullptr, "CS") == false);
assert(::jnp1::encstrset_remove(s0, "CS", "") == false);
assert(::jnp1::encstrset_insert(s0, "", "CS") == false);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_insert(s2, "BG", "EE") == true);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_insert(s3, "EE", "X") == true);
assert(::jnp1::encstrset_test(s1, "CS", "FL") == false);
::jnp1::encstrset_copy(s2, s0);
assert(::jnp1::encstrset_test(s0, "CS", "X") == false);
::jnp1::encstrset_copy(s3, s3);
::jnp1::encstrset_copy(s2, s3);
assert(::jnp1::encstrset_insert(s1, "PSL", "BSTB") == true);
assert(::jnp1::encstrset_size(s4) == 12);
assert(::jnp1::encstrset_insert(s4, "PSL", nullptr) == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_insert(s4, nullptr, NULL) == false);
assert(::jnp1::encstrset_insert(s2, "PSL", "CS") == true);
::jnp1::encstrset_copy(s2, s2);
assert(::jnp1::encstrset_insert(s3, NULL, "FL") == false);
assert(::jnp1::encstrset_test(s2, nullptr, "EE") == false);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_insert(s4, "BUBT", "BSTB") == true);
assert(::jnp1::encstrset_test(21372137, "CS", "BUBT") == false);
::jnp1::encstrset_copy(s2, s3);
::jnp1::encstrset_copy(s0, s1);
::jnp1::encstrset_copy(s2, s3);
assert(::jnp1::encstrset_insert(s3, "", "") == true);
assert(::jnp1::encstrset_remove(s2, "EE", nullptr) == false);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_test(s3, "EE", "BG") == true);
assert(::jnp1::encstrset_insert(s0, "BUBT", NULL) == true);
assert(::jnp1::encstrset_insert(s4, "", "BG") == true);
assert(::jnp1::encstrset_insert(s4, "PSL", nullptr) == true);
assert(::jnp1::encstrset_size(s3) == 3);
assert(::jnp1::encstrset_insert(s4, "", "EE") == false);
assert(::jnp1::encstrset_size(s0) == 7);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_remove(s4, "PSL", "PSL") == false);
assert(::jnp1::encstrset_test(s1, NULL, "BSTB") == false);
assert(::jnp1::encstrset_insert(s3, "CS", "BG") == true);
assert(::jnp1::encstrset_test(21372137, nullptr, "BSTB") == false);
::jnp1::encstrset_copy(21372137, 21372137);
assert(::jnp1::encstrset_insert(s0, "BG", "BG") == true);
assert(::jnp1::encstrset_insert(s2, "", "BSTB") == true);
assert(::jnp1::encstrset_test(s0, NULL, "PSL") == false);
assert(::jnp1::encstrset_size(s2) == 3);
assert(::jnp1::encstrset_test(s1, "BSTB", "CS") == false);
assert(::jnp1::encstrset_size(s2) == 3);
assert(::jnp1::encstrset_test(s1, "BG", NULL) == false);
::jnp1::encstrset_copy(s1, s4);
assert(::jnp1::encstrset_size(s0) == 8);
assert(::jnp1::encstrset_test(s3, "BSTB", "CS") == false);
assert(::jnp1::encstrset_size(s0) == 8);
assert(::jnp1::encstrset_test(s4, nullptr, "") == false);
assert(::jnp1::encstrset_test(s0, "BUBT", NULL) == true);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_test(s3, "", "BG") == true);
assert(::jnp1::encstrset_insert(s1, "", "BG") == true);
assert(::jnp1::encstrset_test(s2, "BUBT", "BSTB") == false);
assert(::jnp1::encstrset_remove(21372137, "PSL", "BSTB") == false);
assert(::jnp1::encstrset_remove(s3, "BSTB", NULL) == false);
assert(::jnp1::encstrset_insert(s4, "", "BSTB") == false);
::jnp1::encstrset_clear(s2);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_size(s0) == 8);
assert(::jnp1::encstrset_insert(21372137, "BG", NULL) == false);
assert(::jnp1::encstrset_size(s0) == 8);
assert(::jnp1::encstrset_insert(s1, NULL, "BUBT") == false);
assert(::jnp1::encstrset_insert(s3, "BUBT", "CS") == true);
::jnp1::encstrset_copy(s3, s2);
::jnp1::encstrset_copy(s0, s4);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_remove(s3, nullptr, NULL) == false);
assert(::jnp1::encstrset_test(s1, "", "EE") == true);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_insert(s4, "CS", "") == true);
assert(::jnp1::encstrset_size(s3) == 5);
assert(::jnp1::encstrset_size(s1) == 1);
assert(::jnp1::encstrset_insert(21372137, nullptr, "") == false);
assert(::jnp1::encstrset_insert(s0, "EE", "BUBT") == true);
assert(::jnp1::encstrset_remove(s4, "PSL", "BSTB") == false);
::jnp1::encstrset_clear(s2);
::jnp1::encstrset_copy(s4, s0);
assert(::jnp1::encstrset_insert(s2, "BUBT", "BUBT") == true);
assert(::jnp1::encstrset_insert(s3, "CS", "PSL") == true);
assert(::jnp1::encstrset_insert(s4, "X", "BG") == true);
assert(::jnp1::encstrset_test(s4, "X", "EE") == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_remove(s0, "BSTB", NULL) == false);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_remove(s1, "EE", "BSTB") == false);
assert(::jnp1::encstrset_test(21372137, "BG", "PSL") == false);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_remove(s1, NULL, "PSL") == false);
assert(::jnp1::encstrset_test(s2, "BUBT", "X") == false);
assert(::jnp1::encstrset_remove(s4, "BG", "PSL") == false);
assert(::jnp1::encstrset_insert(s4, "X", "PSL") == true);
assert(::jnp1::encstrset_insert(s1, nullptr, "") == false);
assert(::jnp1::encstrset_insert(21372137, "FL", "") == false);
::jnp1::encstrset_copy(s0, s1);
::jnp1::encstrset_clear(s3);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_test(s2, "PSL", NULL) == false);
assert(::jnp1::encstrset_remove(s4, "EE", nullptr) == false);
assert(::jnp1::encstrset_insert(s0, "FL", "X") == true);
assert(::jnp1::encstrset_insert(s2, "BG", "EE") == true);
::jnp1::encstrset_copy(s4, s4);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_copy(21372137, s3);
::jnp1::encstrset_copy(21372137, s2);
::jnp1::encstrset_clear(21372137);
::jnp1::encstrset_copy(s0, 21372137);
::jnp1::encstrset_copy(s4, s1);
assert(::jnp1::encstrset_remove(21372137, NULL, "PSL") == false);
::jnp1::encstrset_copy(s0, s3);
::jnp1::encstrset_copy(21372137, s1);
::jnp1::encstrset_copy(s4, 21372137);
assert(::jnp1::encstrset_insert(s1, nullptr, "") == false);
assert(::jnp1::encstrset_remove(s4, "BG", NULL) == false);
assert(::jnp1::encstrset_insert(s2, "", "FL") == true);
assert(::jnp1::encstrset_size(s4) == 0);
assert(::jnp1::encstrset_remove(s4, "FL", "EE") == false);
assert(::jnp1::encstrset_insert(s1, "X", NULL) == true);
assert(::jnp1::encstrset_insert(s3, "BG", "FL") == true);
assert(::jnp1::encstrset_test(21372137, "PSL", "CS") == false);
::jnp1::encstrset_copy(s2, s1);
assert(::jnp1::encstrset_insert(21372137, "", "") == false);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_size(s0) == 11);
assert(::jnp1::encstrset_test(21372137, "PSL", "BUBT") == false);
assert(::jnp1::encstrset_insert(s0, "EE", "FL") == true);
::jnp1::encstrset_copy(s0, s0);
assert(::jnp1::encstrset_insert(s4, "FL", "BG") == true);
assert(::jnp1::encstrset_insert(s1, "", "") == true);
assert(::jnp1::encstrset_test(s1, "", "X") == true);
assert(::jnp1::encstrset_insert(s1, "FL", NULL) == true);
assert(::jnp1::encstrset_insert(s2, nullptr, "BG") == false);
assert(::jnp1::encstrset_insert(s1, "BSTB", "BUBT") == true);
::jnp1::encstrset_copy(s1, s0);
assert(::jnp1::encstrset_test(s1, "", "PSL") == true);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_size(s0) == 13);
assert(::jnp1::encstrset_insert(s0, "FL", "BUBT") == true);
::jnp1::encstrset_copy(s2, s0);
assert(::jnp1::encstrset_insert(s2, "BUBT", "") == true);
assert(::jnp1::encstrset_insert(21372137, nullptr, "CS") == false);
assert(::jnp1::encstrset_insert(s2, "BSTB", "BUBT") == true);
::jnp1::encstrset_copy(s0, s2);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_insert(s4, "PSL", "BUBT") == true);
assert(::jnp1::encstrset_remove(s4, "FL", nullptr) == false);
::jnp1::encstrset_clear(s0);
::jnp1::encstrset_copy(s1, s2);
::jnp1::encstrset_copy(s2, 21372137);
::jnp1::encstrset_clear(s2);
::jnp1::encstrset_copy(21372137, s1);
assert(::jnp1::encstrset_insert(s0, NULL, "EE") == false);
assert(::jnp1::encstrset_remove(21372137, "BSTB", "X") == false);
assert(::jnp1::encstrset_size(s1) == 3);
assert(::jnp1::encstrset_remove(s4, "X", "PSL") == false);
assert(::jnp1::encstrset_size(s1) == 3);
::jnp1::encstrset_copy(s3, 21372137);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_size(s0) == 0);
assert(::jnp1::encstrset_remove(s2, "BUBT", "") == false);
assert(::jnp1::encstrset_insert(s3, "BG", "X") == true);
assert(::jnp1::encstrset_insert(s0, "BUBT", "") == true);
assert(::jnp1::encstrset_insert(s4, "", nullptr) == true);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_clear(s2);
::jnp1::encstrset_clear(21372137);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_insert(s1, "BG", "") == true);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_insert(21372137, "FL", "PSL") == false);
assert(::jnp1::encstrset_insert(s1, "FL", "") == false);
assert(::jnp1::encstrset_insert(s3, "FL", "BSTB") == true);
assert(::jnp1::encstrset_insert(s1, "EE", "FL") == true);
assert(::jnp1::encstrset_insert(s0, "CS", "BSTB") == true);
::jnp1::encstrset_copy(s0, s4);
::jnp1::encstrset_clear(s4);
::jnp1::encstrset_copy(s2, 21372137);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_insert(21372137, "PSL", "EE") == false);
assert(::jnp1::encstrset_insert(21372137, "CS", "BG") == false);
assert(::jnp1::encstrset_insert(s2, "", "") == true);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_insert(s0, "EE", "BSTB") == true);
assert(::jnp1::encstrset_size(s0) == 3);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_test(s4, "BSTB", "BSTB") == false);
assert(::jnp1::encstrset_insert(s3, "", "PSL") == true);
assert(::jnp1::encstrset_insert(s0, "PSL", "BSTB") == true);
assert(::jnp1::encstrset_size(s2) == 0);
assert(::jnp1::encstrset_remove(21372137, nullptr, "") == false);
assert(::jnp1::encstrset_remove(s1, "EE", "X") == false);
assert(::jnp1::encstrset_insert(s3, "BG", "X") == false);
assert(::jnp1::encstrset_size(s1) == 5);
::jnp1::encstrset_copy(s0, s0);
assert(::jnp1::encstrset_insert(21372137, "FL", "CS") == false);
assert(::jnp1::encstrset_remove(s2, "BSTB", "PSL") == false);
assert(::jnp1::encstrset_insert(s1, "BG", "BG") == true);
assert(::jnp1::encstrset_insert(21372137, "EE", nullptr) == false);
assert(::jnp1::encstrset_test(s1, "FL", "FL") == true);
assert(::jnp1::encstrset_insert(s4, "CS", "BG") == true);
::jnp1::encstrset_copy(s0, s3);
::jnp1::encstrset_copy(s0, s0);
assert(::jnp1::encstrset_test(s0, NULL, "FL") == false);
assert(::jnp1::encstrset_insert(s3, "BSTB", NULL) == true);
assert(::jnp1::encstrset_remove(s1, "PSL", NULL) == false);
assert(::jnp1::encstrset_test(s0, nullptr, "X") == false);
::jnp1::encstrset_copy(s4, 21372137);
assert(::jnp1::encstrset_size(s1) == 6);
::jnp1::encstrset_clear(s0);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_insert(s0, "CS", NULL) == true);
assert(::jnp1::encstrset_test(s4, "EE", "BUBT") == false);
assert(::jnp1::encstrset_test(s0, "", "X") == false);
assert(::jnp1::encstrset_size(s3) == 8);
assert(::jnp1::encstrset_insert(21372137, "X", "X") == false);
assert(::jnp1::encstrset_insert(s0, NULL, "X") == false);
assert(::jnp1::encstrset_insert(s0, "BSTB", "EE") == true);
::jnp1::encstrset_copy(s1, s1);
assert(::jnp1::encstrset_test(21372137, "FL", "BG") == false);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_copy(s1, 21372137);
assert(::jnp1::encstrset_remove(s3, NULL, "BUBT") == false);
::jnp1::encstrset_copy(s1, s2);
assert(::jnp1::encstrset_size(s1) == 6);
assert(::jnp1::encstrset_insert(21372137, "PSL", "BG") == false);
assert(::jnp1::encstrset_remove(s3, "CS", NULL) == false);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_test(s3, "BG", "FL") == false);
assert(::jnp1::encstrset_insert(s2, "BSTB", NULL) == true);
::jnp1::encstrset_copy(21372137, 21372137);
assert(::jnp1::encstrset_insert(s2, "EE", "BUBT") == true);
assert(::jnp1::encstrset_insert(21372137, "BG", "EE") == false);
assert(::jnp1::encstrset_size(s2) == 8);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_test(s4, "EE", "FL") == false);
assert(::jnp1::encstrset_size(s3) == 0);
assert(::jnp1::encstrset_size(s1) == 0);
assert(::jnp1::encstrset_remove(s4, "PSL", "BSTB") == false);
assert(::jnp1::encstrset_test(s2, NULL, "PSL") == false);
assert(::jnp1::encstrset_test(s1, nullptr, "FL") == false);
assert(::jnp1::encstrset_insert(s4, nullptr, "BG") == false);
assert(::jnp1::encstrset_size(s2) == 8);
assert(::jnp1::encstrset_test(s3, "FL", "") == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_insert(s4, "CS", "BUBT") == true);
assert(::jnp1::encstrset_insert(s4, "X", "CS") == true);
assert(::jnp1::encstrset_remove(21372137, "PSL", "BG") == false);
assert(::jnp1::encstrset_insert(s2, "X", "FL") == true);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_copy(s1, s3);
assert(::jnp1::encstrset_insert(s0, nullptr, "") == false);
assert(::jnp1::encstrset_insert(21372137, "FL", "BSTB") == false);
assert(::jnp1::encstrset_insert(s3, "PSL", "BSTB") == true);
assert(::jnp1::encstrset_remove(s1, "BUBT", nullptr) == false);
assert(::jnp1::encstrset_insert(s3, "PSL", nullptr) == true);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_size(s1) == 0);
assert(::jnp1::encstrset_remove(s4, "", "") == false);
assert(::jnp1::encstrset_size(s2) == 9);
assert(::jnp1::encstrset_remove(s3, "BUBT", "PSL") == false);
assert(::jnp1::encstrset_test(s1, "", "X") == false);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_remove(s2, "PSL", "") == false);
assert(::jnp1::encstrset_insert(s1, "EE", "X") == true);
assert(::jnp1::encstrset_test(s3, "BUBT", "CS") == false);
::jnp1::encstrset_copy(21372137, 21372137);
assert(::jnp1::encstrset_insert(s1, nullptr, "BUBT") == false);
assert(::jnp1::encstrset_insert(s1, "CS", "") == true);
assert(::jnp1::encstrset_size(s1) == 2);
assert(::jnp1::encstrset_remove(s2, "", "X") == false);
assert(::jnp1::encstrset_insert(s3, "CS", "") == true);
assert(::jnp1::encstrset_size(s3) == 3);
assert(::jnp1::encstrset_insert(s1, "FL", "EE") == true);
assert(::jnp1::encstrset_size(s4) == 3);
assert(::jnp1::encstrset_size(s4) == 3);
assert(::jnp1::encstrset_size(s2) == 0);
::jnp1::encstrset_copy(21372137, s3);
assert(::jnp1::encstrset_size(s2) == 0);
assert(::jnp1::encstrset_test(s0, "FL", "") == false);
assert(::jnp1::encstrset_test(21372137, nullptr, "BUBT") == false);
assert(::jnp1::encstrset_size(s3) == 3);
assert(::jnp1::encstrset_test(21372137, "", "BSTB") == false);
::jnp1::encstrset_copy(s1, 21372137);
::jnp1::encstrset_copy(s3, s1);
assert(::jnp1::encstrset_insert(s3, "BUBT", "") == true);
assert(::jnp1::encstrset_insert(s0, "FL", "X") == true);
assert(::jnp1::encstrset_test(s2, "", "X") == false);
::jnp1::encstrset_copy(s4, s4);
::jnp1::encstrset_copy(s0, s1);
::jnp1::encstrset_clear(s3);
::jnp1::encstrset_copy(s2, 21372137);
assert(::jnp1::encstrset_insert(s1, "CS", nullptr) == false);
::jnp1::encstrset_copy(s1, s2);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_remove(s4, NULL, "BSTB") == false);
::jnp1::encstrset_copy(21372137, 21372137);
assert(::jnp1::encstrset_size(s1) == 7);
assert(::jnp1::encstrset_remove(s1, "BSTB", "") == false);
assert(::jnp1::encstrset_size(s0) == 3);
assert(::jnp1::encstrset_remove(s3, "BUBT", "X") == false);
assert(::jnp1::encstrset_size(s0) == 3);
::jnp1::encstrset_copy(s1, 21372137);
assert(::jnp1::encstrset_insert(s2, "BSTB", NULL) == true);
::jnp1::encstrset_clear(s2);
::jnp1::encstrset_copy(21372137, s0);
assert(::jnp1::encstrset_insert(s1, "PSL", NULL) == false);
assert(::jnp1::encstrset_insert(s3, "X", "X") == true);
assert(::jnp1::encstrset_insert(s0, "X", "BG") == true);
::jnp1::encstrset_copy(s1, 21372137);
assert(::jnp1::encstrset_insert(21372137, "FL", "") == false);
::jnp1::encstrset_copy(s4, s1);
::jnp1::encstrset_copy(21372137, s4);
::jnp1::encstrset_copy(s0, 21372137);
assert(::jnp1::encstrset_insert(s0, nullptr, "EE") == false);
assert(::jnp1::encstrset_test(s1, "", "BG") == false);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_insert(s2, nullptr, "X") == false);
assert(::jnp1::encstrset_remove(21372137, nullptr, "FL") == false);
::jnp1::encstrset_copy(s3, s1);
assert(::jnp1::encstrset_insert(s1, "BG", NULL) == true);
assert(::jnp1::encstrset_insert(21372137, "PSL", NULL) == false);
assert(::jnp1::encstrset_insert(s1, "BSTB", NULL) == true);
::jnp1::encstrset_copy(s0, s2);
assert(::jnp1::encstrset_insert(21372137, NULL, "BUBT") == false);
::jnp1::encstrset_clear(s1);
::jnp1::encstrset_copy(s3, s1);
assert(::jnp1::encstrset_size(s2) == 4);
assert(::jnp1::encstrset_insert(s4, "CS", "") == true);
assert(::jnp1::encstrset_remove(s2, "", "BSTB") == false);
::jnp1::encstrset_copy(s4, s3);
::jnp1::encstrset_copy(s4, s1);
assert(::jnp1::encstrset_insert(s3, "BUBT", "FL") == true);
assert(::jnp1::encstrset_insert(21372137, "BSTB", "PSL") == false);
assert(::jnp1::encstrset_insert(s0, NULL, "PSL") == false);
::jnp1::encstrset_clear(s3);
::jnp1::encstrset_copy(s2, s4);
assert(::jnp1::encstrset_insert(s2, "CS", "BSTB") == true);
assert(::jnp1::encstrset_test(s1, "BUBT", NULL) == false);
assert(::jnp1::encstrset_insert(s3, "FL", NULL) == true);
assert(::jnp1::encstrset_insert(21372137, "", "EE") == false);
assert(::jnp1::encstrset_insert(s4, "", "CS") == true);
assert(::jnp1::encstrset_remove(s2, "PSL", "") == false);
assert(::jnp1::encstrset_remove(s0, "BUBT", "BG") == false);
::jnp1::encstrset_clear(s0);
assert(::jnp1::encstrset_insert(s4, "EE", "CS") == true);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_size(s4) == 9);
assert(::jnp1::encstrset_size(s2) == 5);
assert(::jnp1::encstrset_size(s0) == 0);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_test(s1, nullptr, "BG") == false);
assert(::jnp1::encstrset_remove(s4, "CS", "FL") == false);
assert(::jnp1::encstrset_insert(s4, "FL", "BG") == true);
::jnp1::encstrset_copy(s0, 21372137);
assert(::jnp1::encstrset_insert(s4, "BSTB", "FL") == true);
assert(::jnp1::encstrset_size(s4) == 11);
assert(::jnp1::encstrset_insert(s0, nullptr, "EE") == false);
assert(::jnp1::encstrset_remove(21372137, "BG", "EE") == false);
assert(::jnp1::encstrset_insert(s3, "BG", "PSL") == true);
assert(::jnp1::encstrset_insert(s4, "EE", nullptr) == true);
::jnp1::encstrset_copy(s3, s3);
assert(::jnp1::encstrset_remove(s3, NULL, "EE") == false);
assert(::jnp1::encstrset_insert(s0, "BUBT", NULL) == true);
assert(::jnp1::encstrset_remove(s0, "CS", "BG") == false);
::jnp1::encstrset_copy(s2, s2);
::jnp1::encstrset_clear(s2);
::jnp1::encstrset_copy(s0, s4);
assert(::jnp1::encstrset_insert(s3, "EE", "BG") == true);
assert(::jnp1::encstrset_insert(s2, "", "FL") == true);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_insert(s2, nullptr, NULL) == false);
assert(::jnp1::encstrset_insert(s4, "", "CS") == false);
::jnp1::encstrset_copy(s3, s0);
::jnp1::encstrset_copy(s0, s4);
assert(::jnp1::encstrset_insert(s2, "", "EE") == false);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_test(s1, NULL, nullptr) == false);
::jnp1::encstrset_copy(s4, s1);
assert(::jnp1::encstrset_insert(21372137, "", "") == false);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_insert(21372137, "", "") == false);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_remove(s3, "FL", nullptr) == false);
assert(::jnp1::encstrset_test(s4, "CS", "BUBT") == false);
assert(::jnp1::encstrset_test(21372137, "X", "CS") == false);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_insert(s3, "PSL", "EE") == true);
::jnp1::encstrset_copy(21372137, s1);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_insert(s3, "BSTB", nullptr) == true);
::jnp1::encstrset_copy(21372137, s3);
::jnp1::encstrset_copy(21372137, s2);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_insert(s1, "PSL", "BG") == true);
assert(::jnp1::encstrset_insert(s3, "CS", "PSL") == true);
assert(::jnp1::encstrset_size(s1) == 1);
assert(::jnp1::encstrset_remove(21372137, "X", "BSTB") == false);
::jnp1::encstrset_clear(s0);
assert(::jnp1::encstrset_insert(s4, "PSL", "X") == true);
::jnp1::encstrset_clear(21372137);
::jnp1::encstrset_copy(s4, s0);
assert(::jnp1::encstrset_size(s3) == 5);
::jnp1::encstrset_copy(s1, s3);
assert(::jnp1::encstrset_insert(s2, "BUBT", "") == true);
assert(::jnp1::encstrset_size(s0) == 1);
::jnp1::encstrset_copy(s0, 21372137);
assert(::jnp1::encstrset_test(s2, "PSL", "BUBT") == false);
assert(::jnp1::encstrset_insert(s0, NULL, "PSL") == false);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_remove(s0, "BUBT", "BG") == false);
assert(::jnp1::encstrset_insert(21372137, "BUBT", "FL") == false);
assert(::jnp1::encstrset_size(s0) == 1);
assert(::jnp1::encstrset_test(21372137, "BG", "PSL") == false);
assert(::jnp1::encstrset_insert(s2, "X", "X") == true);
assert(::jnp1::encstrset_size(s2) == 3);
assert(::jnp1::encstrset_insert(s2, "EE", "EE") == true);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_insert(s2, "EE", "FL") == true);
::jnp1::encstrset_copy(s0, 21372137);
assert(::jnp1::encstrset_insert(21372137, "", "EE") == false);
assert(::jnp1::encstrset_size(s0) == 1);
assert(::jnp1::encstrset_size(s1) == 1);
assert(::jnp1::encstrset_insert(s3, "BSTB", "PSL") == true);
assert(::jnp1::encstrset_insert(s0, "BG", nullptr) == true);
::jnp1::encstrset_copy(s0, s3);
assert(::jnp1::encstrset_size(s3) == 9);
::jnp1::encstrset_clear(s4);
::jnp1::encstrset_copy(s3, s4);
assert(::jnp1::encstrset_insert(s0, "BG", "BUBT") == true);
assert(::jnp1::encstrset_remove(21372137, "BG", "X") == false);
::jnp1::encstrset_copy(s3, s1);
assert(::jnp1::encstrset_size(s4) == 9);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_insert(s2, "", "CS") == false);
assert(::jnp1::encstrset_insert(21372137, "PSL", "PSL") == false);
::jnp1::encstrset_clear(s1);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_remove(s1, "BSTB", "CS") == false);
assert(::jnp1::encstrset_insert(s2, "CS", "BG") == true);
::jnp1::encstrset_copy(21372137, 21372137);
assert(::jnp1::encstrset_size(s0) == 3);
assert(::jnp1::encstrset_insert(21372137, "BSTB", "PSL") == false);
assert(::jnp1::encstrset_insert(21372137, NULL, "") == false);
assert(::jnp1::encstrset_insert(s0, NULL, "CS") == false);
assert(::jnp1::encstrset_insert(s1, "PSL", nullptr) == true);
assert(::jnp1::encstrset_insert(s0, "PSL", "X") == false);
::jnp1::encstrset_copy(s1, s3);
::jnp1::encstrset_clear(s0);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_insert(s1, "CS", "FL") == true);
assert(::jnp1::encstrset_test(s4, "PSL", "X") == true);
assert(::jnp1::encstrset_insert(s1, "X", "EE") == true);
assert(::jnp1::encstrset_test(s2, "PSL", "BUBT") == false);
assert(::jnp1::encstrset_size(s1) == 3);
::jnp1::encstrset_copy(s3, s4);
::jnp1::encstrset_copy(s0, 21372137);
assert(::jnp1::encstrset_insert(s0, "X", "BUBT") == true);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_insert(s3, "BSTB", nullptr) == true);
assert(::jnp1::encstrset_size(s0) == 1);
assert(::jnp1::encstrset_insert(s2, nullptr, nullptr) == false);
::jnp1::encstrset_copy(s2, s3);
assert(::jnp1::encstrset_size(s3) == 1);
::jnp1::encstrset_copy(s1, s2);
assert(::jnp1::encstrset_size(s2) == 3);
assert(::jnp1::encstrset_size(s2) == 3);
assert(::jnp1::encstrset_insert(s0, nullptr, "FL") == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_test(s4, "X", "") == false);
assert(::jnp1::encstrset_size(s2) == 3);
assert(::jnp1::encstrset_size(s4) == 9);
::jnp1::encstrset_copy(s2, s0);
assert(::jnp1::encstrset_insert(s4, "PSL", nullptr) == true);
assert(::jnp1::encstrset_remove(s0, nullptr, "FL") == false);
assert(::jnp1::encstrset_insert(s4, "BSTB", nullptr) == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_insert(21372137, "FL", "CS") == false);
::jnp1::encstrset_copy(s1, s3);
assert(::jnp1::encstrset_test(s4, "BSTB", "PSL") == true);
assert(::jnp1::encstrset_insert(21372137, "EE", "BG") == false);
::jnp1::encstrset_copy(s4, 21372137);
::jnp1::encstrset_copy(s1, s4);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_insert(s4, "BUBT", "FL") == true);
assert(::jnp1::encstrset_insert(s1, "X", nullptr) == true);
assert(::jnp1::encstrset_insert(s2, "CS", "EE") == true);
assert(::jnp1::encstrset_test(21372137, "BUBT", "BUBT") == false);
assert(::jnp1::encstrset_size(s1) == 4);
assert(::jnp1::encstrset_remove(s0, "BG", "BUBT") == false);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_remove(s2, nullptr, "") == false);
assert(::jnp1::encstrset_remove(s4, NULL, "BUBT") == false);
assert(::jnp1::encstrset_insert(s3, "", "FL") == true);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_size(s4) == 13);
::jnp1::encstrset_copy(s2, s0);
::jnp1::encstrset_copy(s2, s1);
assert(::jnp1::encstrset_test(s1, NULL, "CS") == false);
assert(::jnp1::encstrset_insert(s1, "X", "PSL") == true);
assert(::jnp1::encstrset_insert(s2, "PSL", "BG") == true);
::jnp1::encstrset_copy(s0, s1);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_insert(s2, "FL", "CS") == false);
assert(::jnp1::encstrset_remove(s0, "BG", "FL") == false);
assert(::jnp1::encstrset_size(s4) == 13);
assert(::jnp1::encstrset_insert(s1, "", "BSTB") == true);
assert(::jnp1::encstrset_insert(21372137, "PSL", "EE") == false);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_insert(s4, "CS", "X") == true);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_insert(s4, "", "") == true);
assert(::jnp1::encstrset_insert(21372137, "PSL", "BUBT") == false);
assert(::jnp1::encstrset_size(s4) == 15);
assert(::jnp1::encstrset_insert(21372137, "", "EE") == false);
assert(::jnp1::encstrset_remove(s2, NULL, "CS") == false);
assert(::jnp1::encstrset_insert(s4, "CS", "BG") == true);
assert(::jnp1::encstrset_insert(s3, "BG", "") == true);
::jnp1::encstrset_clear(s4);
::jnp1::encstrset_copy(21372137, 21372137);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_size(s0) == 5);
assert(::jnp1::encstrset_insert(s0, "X", "BG") == false);
assert(::jnp1::encstrset_test(s4, "FL", "BSTB") == false);
assert(::jnp1::encstrset_insert(s3, NULL, "BUBT") == false);
assert(::jnp1::encstrset_remove(s4, "FL", "BSTB") == false);
assert(::jnp1::encstrset_insert(s0, "BG", NULL) == true);
assert(::jnp1::encstrset_test(s1, "CS", "BSTB") == false);
assert(::jnp1::encstrset_insert(s1, "", "PSL") == true);
::jnp1::encstrset_copy(s1, s4);
assert(::jnp1::encstrset_size(s2) == 5);
::jnp1::encstrset_copy(21372137, s4);
assert(::jnp1::encstrset_insert(s3, "", "EE") == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_size(s0) == 6);
assert(::jnp1::encstrset_insert(21372137, "BG", "") == false);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_remove(21372137, "FL", "FL") == false);
assert(::jnp1::encstrset_insert(s2, "BUBT", "") == true);
assert(::jnp1::encstrset_size(s2) == 6);
assert(::jnp1::encstrset_insert(s3, "", "X") == false);
::jnp1::encstrset_copy(s0, s0);
assert(::jnp1::encstrset_insert(s3, "", "BUBT") == false);
assert(::jnp1::encstrset_size(s2) == 6);
assert(::jnp1::encstrset_size(s2) == 6);
::jnp1::encstrset_copy(s4, s2);
assert(::jnp1::encstrset_insert(21372137, "", "CS") == false);
assert(::jnp1::encstrset_test(s4, "PSL", NULL) == false);
::jnp1::encstrset_copy(s2, 21372137);
assert(::jnp1::encstrset_size(s2) == 6);
::jnp1::encstrset_copy(21372137, s0);
assert(::jnp1::encstrset_insert(s4, "FL", "EE") == true);
assert(::jnp1::encstrset_insert(21372137, "", "EE") == false);
::jnp1::encstrset_copy(s0, s1);
assert(::jnp1::encstrset_insert(21372137, "BUBT", NULL) == false);
::jnp1::encstrset_copy(s0, s0);
::jnp1::encstrset_copy(21372137, s0);
::jnp1::encstrset_copy(s4, s0);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_remove(s3, "BG", "") == true);
::jnp1::encstrset_copy(s2, s4);
assert(::jnp1::encstrset_remove(s2, "", "BUBT") == false);
::jnp1::encstrset_copy(s4, s2);
assert(::jnp1::encstrset_insert(s2, NULL, "") == false);
assert(::jnp1::encstrset_test(21372137, "BG", "EE") == false);
::jnp1::encstrset_copy(21372137, s1);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_size(s1) == 0);
assert(::jnp1::encstrset_test(s2, "PSL", "BG") == true);
assert(::jnp1::encstrset_test(s1, "", nullptr) == false);
assert(::jnp1::encstrset_insert(s1, "X", NULL) == true);
assert(::jnp1::encstrset_insert(21372137, "BSTB", NULL) == false);
::jnp1::encstrset_copy(21372137, s2);
assert(::jnp1::encstrset_test(s1, "", "") == false);
::jnp1::encstrset_copy(s1, s4);
::jnp1::encstrset_copy(21372137, s1);
assert(::jnp1::encstrset_remove(21372137, "", "") == false);
assert(::jnp1::encstrset_remove(s1, "FL", "PSL") == false);
assert(::jnp1::encstrset_test(s2, "BSTB", "PSL") == false);
assert(::jnp1::encstrset_insert(s1, "BSTB", NULL) == true);
::jnp1::encstrset_copy(s4, s2);
::jnp1::encstrset_clear(s1);
::jnp1::encstrset_copy(s2, s3);
::jnp1::encstrset_copy(s2, s0);
::jnp1::encstrset_copy(21372137, s3);
assert(::jnp1::encstrset_remove(21372137, "BSTB", NULL) == false);
assert(::jnp1::encstrset_insert(s4, "BSTB", "X") == true);
::jnp1::encstrset_copy(s0, s2);
assert(::jnp1::encstrset_test(s0, nullptr, "BG") == false);
assert(::jnp1::encstrset_insert(s0, "PSL", "FL") == true);
assert(::jnp1::encstrset_insert(s2, "", "BG") == true);
assert(::jnp1::encstrset_insert(s4, nullptr, "CS") == false);
::jnp1::encstrset_copy(s2, s3);
assert(::jnp1::encstrset_insert(s0, nullptr, nullptr) == false);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_test(s2, "X", "FL") == false);
assert(::jnp1::encstrset_insert(s0, nullptr, "BSTB") == false);
assert(::jnp1::encstrset_remove(s1, NULL, "X") == false);
assert(::jnp1::encstrset_insert(s0, "FL", "FL") == true);
::jnp1::encstrset_copy(21372137, s0);
assert(::jnp1::encstrset_test(s3, "PSL", "PSL") == false);
::jnp1::encstrset_copy(s1, s4);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_insert(s0, "BG", "") == false);
::jnp1::encstrset_copy(21372137, s1);
assert(::jnp1::encstrset_insert(s2, "EE", "FL") == false);
assert(::jnp1::encstrset_insert(s2, "BUBT", "") == false);
assert(::jnp1::encstrset_insert(s0, "FL", "BG") == true);
::jnp1::encstrset_copy(s2, s3);
assert(::jnp1::encstrset_insert(21372137, "X", "FL") == false);
::jnp1::encstrset_copy(s4, s2);
assert(::jnp1::encstrset_insert(s3, nullptr, "FL") == false);
assert(::jnp1::encstrset_insert(s0, "BUBT", "FL") == true);
assert(::jnp1::encstrset_remove(21372137, "PSL", "EE") == false);
assert(::jnp1::encstrset_insert(s4, "BUBT", "BSTB") == true);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_insert(21372137, "CS", "BG") == false);
assert(::jnp1::encstrset_insert(s0, nullptr, "EE") == false);
assert(::jnp1::encstrset_insert(s0, "", NULL) == true);
assert(::jnp1::encstrset_insert(21372137, NULL, "X") == false);
::jnp1::encstrset_copy(s2, s4);
::jnp1::encstrset_clear(s0);
::jnp1::encstrset_copy(s3, s2);
assert(::jnp1::encstrset_insert(s0, "CS", "EE") == true);
assert(::jnp1::encstrset_size(s4) == 13);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_test(s2, "", "PSL") == true);
assert(::jnp1::encstrset_remove(s1, "EE", "BSTB") == false);
assert(::jnp1::encstrset_remove(s4, "BG", "EE") == false);
::jnp1::encstrset_copy(s2, 21372137);
assert(::jnp1::encstrset_insert(s1, "PSL", "BG") == true);
assert(::jnp1::encstrset_remove(21372137, "EE", NULL) == false);
assert(::jnp1::encstrset_test(s2, "X", "EE") == true);
assert(::jnp1::encstrset_insert(s2, "BUBT", "") == false);
assert(::jnp1::encstrset_insert(s4, "EE", "FL") == false);
assert(::jnp1::encstrset_insert(s0, "CS", "EE") == false);
assert(::jnp1::encstrset_test(s1, "BG", NULL) == false);
::jnp1::encstrset_copy(s3, s2);
::jnp1::encstrset_copy(s1, s2);
::jnp1::encstrset_copy(s1, s3);
assert(::jnp1::encstrset_insert(s4, "FL", "BSTB") == true);
::jnp1::encstrset_clear(s0);
assert(::jnp1::encstrset_test(s4, NULL, "X") == false);
assert(::jnp1::encstrset_test(s1, "BUBT", "CS") == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_insert(s4, "X", "FL") == true);
assert(::jnp1::encstrset_insert(s3, "FL", "BUBT") == true);
::jnp1::encstrset_copy(s3, s1);
assert(::jnp1::encstrset_remove(s1, "PSL", "X") == false);
assert(::jnp1::encstrset_size(s0) == 0);
::jnp1::encstrset_copy(s2, s3);
::jnp1::encstrset_copy(s1, 21372137);
assert(::jnp1::encstrset_insert(s0, nullptr, "EE") == false);
::jnp1::encstrset_clear(s4);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_size(s1) == 2);
assert(::jnp1::encstrset_remove(s3, "X", "BUBT") == true);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_clear(21372137);
::jnp1::encstrset_copy(21372137, s1);
assert(::jnp1::encstrset_insert(s0, "FL", "") == true);
::jnp1::encstrset_copy(s2, s3);
::jnp1::encstrset_copy(s3, s1);
assert(::jnp1::encstrset_test(s2, NULL, "") == false);
assert(::jnp1::encstrset_insert(s0, "BSTB", "BSTB") == true);
::jnp1::encstrset_copy(s1, s2);
::jnp1::encstrset_copy(s4, s1);
assert(::jnp1::encstrset_remove(s0, "", "") == false);
assert(::jnp1::encstrset_remove(s2, "BG", "PSL") == false);
assert(::jnp1::encstrset_insert(s0, "EE", NULL) == true);
assert(::jnp1::encstrset_insert(s0, "BSTB", "X") == true);
::jnp1::encstrset_copy(s1, s3);
assert(::jnp1::encstrset_remove(s0, "X", "BG") == false);
assert(::jnp1::encstrset_insert(s1, "", NULL) == false);
::jnp1::encstrset_copy(21372137, s2);
assert(::jnp1::encstrset_test(s0, "", "X") == false);
assert(::jnp1::encstrset_insert(21372137, "X", "") == false);
::jnp1::encstrset_copy(21372137, s4);
::jnp1::encstrset_copy(s4, s4);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_remove(s2, "", "EE") == true);
assert(::jnp1::encstrset_remove(s3, "X", "BUBT") == true);
assert(::jnp1::encstrset_insert(s0, "PSL", "EE") == true);
assert(::jnp1::encstrset_insert(s3, "BSTB", "CS") == true);
::jnp1::encstrset_copy(s1, 21372137);
assert(::jnp1::encstrset_test(s4, "BUBT", "") == false);
assert(::jnp1::encstrset_test(s1, "", nullptr) == false);
assert(::jnp1::encstrset_insert(s2, "FL", "BSTB") == true);
assert(::jnp1::encstrset_remove(21372137, "BUBT", "") == false);
assert(::jnp1::encstrset_size(s4) == 0);
assert(::jnp1::encstrset_insert(s3, "FL", "EE") == false);
::jnp1::encstrset_copy(s4, s4);
assert(::jnp1::encstrset_remove(s2, "", "CS") == false);
assert(::jnp1::encstrset_remove(s0, "BUBT", "PSL") == false);
::jnp1::encstrset_copy(21372137, s0);
assert(::jnp1::encstrset_insert(21372137, nullptr, "") == false);
assert(::jnp1::encstrset_size(s4) == 0);
::jnp1::encstrset_copy(s2, 21372137);
assert(::jnp1::encstrset_remove(s2, "PSL", nullptr) == true);
assert(::jnp1::encstrset_remove(s2, "", "PSL") == false);
assert(::jnp1::encstrset_insert(21372137, NULL, "BSTB") == false);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_insert(21372137, "BSTB", "PSL") == false);
assert(::jnp1::encstrset_insert(s2, "CS", "CS") == true);
assert(::jnp1::encstrset_remove(s3, "BUBT", "PSL") == false);
assert(::jnp1::encstrset_insert(s2, "CS", "BG") == true);
assert(::jnp1::encstrset_test(s0, "", "PSL") == false);
assert(::jnp1::encstrset_test(s4, "EE", "BSTB") == false);
::jnp1::encstrset_copy(21372137, s3);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_size(s2) == 14);
assert(::jnp1::encstrset_remove(21372137, "BSTB", "CS") == false);
assert(::jnp1::encstrset_insert(s1, "BUBT", "BSTB") == true);
assert(::jnp1::encstrset_size(s0) == 5);
assert(::jnp1::encstrset_test(s1, "BG", nullptr) == false);
assert(::jnp1::encstrset_insert(s3, "EE", "EE") == true);
assert(::jnp1::encstrset_remove(s0, "", "BG") == false);
assert(::jnp1::encstrset_insert(s3, "X", "") == false);
assert(::jnp1::encstrset_insert(s3, "EE", nullptr) == true);
::jnp1::encstrset_copy(s4, s1);
::jnp1::encstrset_copy(s2, s1);
assert(::jnp1::encstrset_size(s1) == 15);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_insert(s3, "BUBT", "") == false);
assert(::jnp1::encstrset_insert(21372137, "BG", "PSL") == false);
assert(::jnp1::encstrset_test(21372137, "PSL", NULL) == false);
assert(::jnp1::encstrset_test(s3, nullptr, NULL) == false);
::jnp1::encstrset_copy(s3, s2);
::jnp1::encstrset_copy(s1, 21372137);
assert(::jnp1::encstrset_test(s2, "BG", "CS") == false);
assert(::jnp1::encstrset_test(21372137, "CS", "EE") == false);
assert(::jnp1::encstrset_insert(s1, NULL, "BG") == false);
assert(::jnp1::encstrset_remove(s3, "EE", nullptr) == true);
assert(::jnp1::encstrset_test(s3, "EE", "") == false);
assert(::jnp1::encstrset_remove(21372137, "BSTB", "BG") == false);
assert(::jnp1::encstrset_size(s2) == 15);
assert(::jnp1::encstrset_insert(s1, "FL", "FL") == false);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_test(s3, "EE", "CS") == true);
assert(::jnp1::encstrset_size(s2) == 15);
assert(::jnp1::encstrset_remove(s0, "BSTB", "") == false);
assert(::jnp1::encstrset_remove(s1, "BSTB", NULL) == false);
assert(::jnp1::encstrset_insert(21372137, "BSTB", "PSL") == false);
assert(::jnp1::encstrset_remove(s4, "EE", "") == false);
::jnp1::encstrset_copy(s0, s2);
assert(::jnp1::encstrset_remove(s3, "CS", "X") == false);
::jnp1::encstrset_copy(s2, s0);
assert(::jnp1::encstrset_insert(s3, "CS", "BSTB") == true);
assert(::jnp1::encstrset_insert(s3, "PSL", "FL") == true);
::jnp1::encstrset_copy(s0, s0);
assert(::jnp1::encstrset_insert(s3, "", NULL) == false);
assert(::jnp1::encstrset_insert(21372137, "EE", "EE") == false);
::jnp1::encstrset_copy(s4, s0);
::jnp1::encstrset_copy(s1, s2);
assert(::jnp1::encstrset_insert(s4, "", "BSTB") == true);
assert(::jnp1::encstrset_size(s4) == 1);
assert(::jnp1::encstrset_size(s1) == 15);
assert(::jnp1::encstrset_insert(s2, NULL, nullptr) == false);
assert(::jnp1::encstrset_size(s4) == 1);
assert(::jnp1::encstrset_size(s2) == 22);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_remove(21372137, "FL", "") == false);
assert(::jnp1::encstrset_size(s1) == 15);
assert(::jnp1::encstrset_size(s3) == 16);
assert(::jnp1::encstrset_test(s2, "EE", NULL) == true);
assert(::jnp1::encstrset_test(s4, "BSTB", "BG") == false);
assert(::jnp1::encstrset_insert(s2, "FL", nullptr) == false);
assert(::jnp1::encstrset_remove(s3, "EE", "CS") == true);
::jnp1::encstrset_copy(s0, 21372137);
assert(::jnp1::encstrset_size(s1) == 15);
assert(::jnp1::encstrset_insert(s2, "", "") == false);
assert(::jnp1::encstrset_insert(s2, "FL", "FL") == false);
::jnp1::encstrset_copy(s3, s4);
assert(::jnp1::encstrset_remove(21372137, "FL", "EE") == false);
assert(::jnp1::encstrset_remove(21372137, NULL, "CS") == false);
assert(::jnp1::encstrset_remove(s0, "FL", NULL) == true);
assert(::jnp1::encstrset_test(21372137, "X", NULL) == false);
assert(::jnp1::encstrset_insert(s3, "PSL", "BUBT") == true);
assert(::jnp1::encstrset_size(21372137) == 0);
::jnp1::encstrset_copy(s4, s1);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_insert(s2, "", "CS") == false);
assert(::jnp1::encstrset_insert(s3, "CS", "X") == true);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_size(s2) == 22);
assert(::jnp1::encstrset_insert(s3, "BSTB", "FL") == true);
::jnp1::encstrset_copy(s1, s2);
::jnp1::encstrset_clear(s0);
assert(::jnp1::encstrset_insert(s3, "BSTB", "FL") == false);
::jnp1::encstrset_copy(s1, s4);
assert(::jnp1::encstrset_insert(s3, "PSL", "PSL") == true);
::jnp1::encstrset_copy(s1, 21372137);
::jnp1::encstrset_clear(s4);
::jnp1::encstrset_clear(s3);
::jnp1::encstrset_clear(s0);
::jnp1::encstrset_copy(s0, s3);
assert(::jnp1::encstrset_remove(s1, "BUBT", nullptr) == false);
::jnp1::encstrset_copy(21372137, s0);
assert(::jnp1::encstrset_insert(s4, "BG", "EE") == true);
::jnp1::encstrset_clear(s3);
assert(::jnp1::encstrset_size(s3) == 0);
assert(::jnp1::encstrset_remove(s2, "BSTB", "BUBT") == true);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_remove(s0, "X", "EE") == false);
::jnp1::encstrset_copy(s4, s2);
assert(::jnp1::encstrset_test(s0, "X", nullptr) == false);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_remove(s1, "PSL", "") == false);
::jnp1::encstrset_copy(s0, s3);
::jnp1::encstrset_clear(21372137);
::jnp1::encstrset_clear(s1);
::jnp1::encstrset_copy(s0, s4);
assert(::jnp1::encstrset_test(s4, "EE", "BG") == true);
assert(::jnp1::encstrset_size(s3) == 0);
assert(::jnp1::encstrset_insert(s4, "CS", "X") == true);
assert(::jnp1::encstrset_test(s3, "", "CS") == false);
assert(::jnp1::encstrset_insert(s0, "X", "X") == true);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_insert(s2, "", "PSL") == false);
assert(::jnp1::encstrset_insert(21372137, "BUBT", "") == false);
::jnp1::encstrset_copy(s3, s0);
assert(::jnp1::encstrset_insert(21372137, "PSL", "PSL") == false);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_test(s3, "BG", "") == false);
assert(::jnp1::encstrset_remove(s0, "BUBT", "BUBT") == false);
assert(::jnp1::encstrset_insert(s4, "PSL", "PSL") == true);
assert(::jnp1::encstrset_size(s0) == 1);
assert(::jnp1::encstrset_insert(s3, "BUBT", "CS") == true);
assert(::jnp1::encstrset_insert(s0, "FL", "BG") == true);
assert(::jnp1::encstrset_insert(21372137, "BUBT", "X") == false);
assert(::jnp1::encstrset_test(s2, "FL", "EE") == false);
assert(::jnp1::encstrset_test(s0, "PSL", "BG") == false);
assert(::jnp1::encstrset_insert(s3, "BG", "") == true);
assert(::jnp1::encstrset_insert(s1, "", nullptr) == true);
::jnp1::encstrset_copy(s2, s1);
assert(::jnp1::encstrset_insert(s2, "", nullptr) == true);
assert(::jnp1::encstrset_test(s1, "X", "EE") == false);
assert(::jnp1::encstrset_test(s1, "", "BUBT") == true);
assert(::jnp1::encstrset_size(s2) == 1);
assert(::jnp1::encstrset_size(s4) == 3);
assert(::jnp1::encstrset_test(s1, "", "") == true);
::jnp1::encstrset_copy(s0, s2);
::jnp1::encstrset_clear(21372137);
assert(::jnp1::encstrset_remove(s0, "PSL", NULL) == false);
assert(::jnp1::encstrset_test(s1, NULL, nullptr) == false);
::jnp1::encstrset_copy(s3, 21372137);
assert(::jnp1::encstrset_insert(s1, "", NULL) == false);
::jnp1::encstrset_copy(s2, s0);
::jnp1::encstrset_copy(s1, s4);
assert(::jnp1::encstrset_remove(s0, nullptr, "X") == false);
assert(::jnp1::encstrset_test(s0, "EE", NULL) == false);
assert(::jnp1::encstrset_insert(s3, NULL, "BG") == false);
assert(::jnp1::encstrset_remove(21372137, "", "BSTB") == false);
assert(::jnp1::encstrset_insert(s1, "", "BSTB") == false);
assert(::jnp1::encstrset_insert(s1, "BUBT", "BSTB") == true);
assert(::jnp1::encstrset_size(s2) == 3);
assert(::jnp1::encstrset_insert(s0, "BG", nullptr) == true);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_test(s3, "FL", "EE") == false);
::jnp1::encstrset_copy(s0, 21372137);
assert(::jnp1::encstrset_insert(s4, "CS", "") == true);
::jnp1::encstrset_clear(s1);
assert(::jnp1::encstrset_size(s3) == 2);
assert(::jnp1::encstrset_insert(s0, "EE", nullptr) == true);
assert(::jnp1::encstrset_test(s4, "BSTB", "FL") == false);
::jnp1::encstrset_copy(s3, s3);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_remove(s4, nullptr, "PSL") == false);
assert(::jnp1::encstrset_remove(s1, "PSL", "X") == false);
::jnp1::encstrset_clear(s3);
::jnp1::encstrset_copy(s4, s4);
assert(::jnp1::encstrset_test(s3, "CS", "EE") == false);
::jnp1::encstrset_copy(s3, s3);
assert(::jnp1::encstrset_test(s4, "EE", "X") == false);
assert(::jnp1::encstrset_insert(21372137, "", NULL) == false);
::jnp1::encstrset_copy(21372137, s4);
assert(::jnp1::encstrset_insert(21372137, "", "X") == false);
assert(::jnp1::encstrset_insert(21372137, "X", "CS") == false);
assert(::jnp1::encstrset_insert(s0, "PSL", "BG") == true);
assert(::jnp1::encstrset_size(s1) == 0);
::jnp1::encstrset_clear(s4);
assert(::jnp1::encstrset_insert(s2, "BUBT", "BSTB") == true);
::jnp1::encstrset_clear(s3);
::jnp1::encstrset_copy(21372137, s3);
::jnp1::encstrset_copy(s0, s2);
::jnp1::encstrset_copy(s0, s0);
assert(::jnp1::encstrset_test(s2, "FL", NULL) == false);
assert(::jnp1::encstrset_insert(s2, "FL", NULL) == true);
assert(::jnp1::encstrset_size(s2) == 8);
assert(::jnp1::encstrset_remove(s3, "BG", nullptr) == false);
::jnp1::encstrset_copy(21372137, s2);
::jnp1::encstrset_copy(21372137, s3);
assert(::jnp1::encstrset_insert(s0, "PSL", "FL") == true);
::jnp1::encstrset_copy(s3, s1);
assert(::jnp1::encstrset_insert(s3, "PSL", "CS") == true);
::jnp1::encstrset_copy(s3, s2);
assert(::jnp1::encstrset_remove(s1, "CS", "CS") == false);
::jnp1::encstrset_copy(s1, s4);
assert(::jnp1::encstrset_remove(s0, nullptr, "BG") == false);
assert(::jnp1::encstrset_remove(s1, NULL, NULL) == false);
assert(::jnp1::encstrset_test(s4, "BSTB", "BUBT") == false);
::jnp1::encstrset_copy(s4, s3);
::jnp1::encstrset_copy(s0, s2);
::jnp1::encstrset_copy(s4, s0);
::jnp1::encstrset_copy(s0, 21372137);
::jnp1::encstrset_copy(s0, s3);
::jnp1::encstrset_copy(21372137, s4);
assert(::jnp1::encstrset_insert(21372137, "PSL", "FL") == false);
assert(::jnp1::encstrset_size(s1) == 0);
assert(::jnp1::encstrset_insert(s0, "", nullptr) == false);
assert(::jnp1::encstrset_size(s1) == 0);
assert(::jnp1::encstrset_insert(s3, "BG", "PSL") == true);
::jnp1::encstrset_clear(s2);
::jnp1::encstrset_copy(s1, s1);
assert(::jnp1::encstrset_insert(21372137, "PSL", "") == false);
::jnp1::encstrset_copy(s4, s0);
assert(::jnp1::encstrset_remove(21372137, "BUBT", "") == false);
assert(::jnp1::encstrset_insert(s3, "BG", "X") == true);
assert(::jnp1::encstrset_insert(s4, NULL, "BUBT") == false);
assert(::jnp1::encstrset_insert(s3, "EE", "BG") == true);
assert(::jnp1::encstrset_remove(s3, "CS", nullptr) == false);
assert(::jnp1::encstrset_insert(21372137, "X", "CS") == false);
::jnp1::encstrset_copy(s0, s0);
assert(::jnp1::encstrset_insert(s1, nullptr, "CS") == false);
assert(::jnp1::encstrset_remove(s2, nullptr, nullptr) == false);
assert(::jnp1::encstrset_insert(s2, "EE", "FL") == true);
::jnp1::encstrset_clear(s2);
assert(::jnp1::encstrset_insert(s4, nullptr, "PSL") == false);
::jnp1::encstrset_copy(s0, s0);
assert(::jnp1::encstrset_insert(s4, "", "X") == true);
assert(::jnp1::encstrset_remove(s0, "X", "CS") == false);
assert(::jnp1::encstrset_remove(s3, "EE", "") == true);
::jnp1::encstrset_copy(s1, s0);
assert(::jnp1::encstrset_insert(s3, "BG", "PSL") == false);
assert(::jnp1::encstrset_size(s4) == 1);
assert(::jnp1::encstrset_size(s4) == 1);
assert(::jnp1::encstrset_insert(s2, "BG", "PSL") == true);
assert(::jnp1::encstrset_size(s3) == 10);
assert(::jnp1::encstrset_insert(21372137, "BSTB", "BUBT") == false);
::jnp1::encstrset_copy(s1, s2);
assert(::jnp1::encstrset_insert(s4, nullptr, NULL) == false);
::jnp1::encstrset_copy(s4, s3);
assert(::jnp1::encstrset_insert(s1, "BSTB", "FL") == true);
::jnp1::encstrset_copy(21372137, s0);
assert(::jnp1::encstrset_insert(s4, "FL", NULL) == true);
assert(::jnp1::encstrset_insert(21372137, "BG", NULL) == false);
assert(::jnp1::encstrset_remove(s1, nullptr, "") == false);
assert(::jnp1::encstrset_insert(s1, "X", "BG") == true);
assert(::jnp1::encstrset_remove(21372137, "EE", "CS") == false);
assert(::jnp1::encstrset_size(s2) == 1);
assert(::jnp1::encstrset_insert(s0, "BSTB", "BUBT") == true);
assert(::jnp1::encstrset_insert(21372137, "BUBT", "EE") == false);
assert(::jnp1::encstrset_test(21372137, "PSL", "") == false);
assert(::jnp1::encstrset_insert(21372137, NULL, "CS") == false);
assert(::jnp1::encstrset_insert(21372137, "BG", "X") == false);
assert(::jnp1::encstrset_size(s4) == 2);
assert(::jnp1::encstrset_test(s1, "", "FL") == false);
assert(::jnp1::encstrset_size(21372137) == 0);
assert(::jnp1::encstrset_insert(s0, "BG", "FL") == false);
assert(::jnp1::encstrset_test(s2, "BSTB", "CS") == false);
::jnp1::encstrset_copy(s4, s2);
assert(::jnp1::encstrset_insert(s0, nullptr, "BSTB") == false);
assert(::jnp1::encstrset_size(s2) == 3);
assert(::jnp1::encstrset_insert(s2, "EE", "FL") == true);
::jnp1::encstrset_copy(s3, s4);
assert(::jnp1::encstrset_size(s4) == 11);
::jnp1::encstrset_clear(s0);
::jnp1::encstrset_copy(s4, 21372137);
::jnp1::encstrset_clear(s4);
::jnp1::encstrset_copy(s3, s1);
::jnp1::encstrset_copy(s4, s3);
::jnp1::encstrset_copy(s3, s3);
assert(::jnp1::encstrset_insert(s4, "", "EE") == true);
assert(::jnp1::encstrset_insert(21372137, "BG", "X") == false);
assert(::jnp1::encstrset_insert(s1, "BG", "") == false);
assert(::jnp1::encstrset_size(s3) == 10);
::jnp1::encstrset_copy(s3, 21372137);
assert(::jnp1::encstrset_insert(s1, "BSTB", "EE") == true);
assert(::jnp1::encstrset_remove(s2, "BSTB", "") == false);
::jnp1::encstrset_copy(s2, s4);
assert(::jnp1::encstrset_insert(s1, nullptr, "BG") == false);
assert(::jnp1::encstrset_insert(21372137, "PSL", "BSTB") == false);
assert(::jnp1::encstrset_remove(s0, "BUBT", nullptr) == false);
assert(::jnp1::encstrset_insert(s3, "BUBT", "BUBT") == true);
assert(::jnp1::encstrset_insert(s1, "", NULL) == false);
assert(::jnp1::encstrset_remove(21372137, "BSTB", "X") == false);
assert(::jnp1::encstrset_insert(s2, nullptr, "") == false);
}
